---
title: "Breast Cancer Diagnosis Classification Analysis"
author: AUSTIN'S TEMPLATE
date: "December 9th, 2022"
output: 
  pdf_document:
    toc: TRUE
    toc_depth: 2
    number_sections: TRUE
    df_print: paged
    fig_caption: TRUE
    highlight: tango
---
```{r setup, include=FALSE}
# Import packages
library(tidyverse)
library(ggplot2)
library(GGally)
library(knitr)
library(boot)
library(caret)
library(randomForest)
library(e1071)
library(class)
set.seed(420)
data <- read.csv("breast_cancer_diagnostic_data.csv") # Full Data
training <- read.csv("training.csv") # Training Data
test <- read.csv("test.csv")  # Test Data
```

# Background (Should we do an Abstract?)

In our analysis, we will be using the Breast Cancer Wisconsin (Diagnostic) Data Set from Kaggle. 
This data set contains 569 observations of breast cancer cells with 32 variables describing each cell. 
Some of the variables include characteristics like radius, texture, area, perimeter of the cell.

# Data

*Insert text here*

## Variable Descriptions

*Insert text here*

# Explatory Data Analysis

*Insert text here*






# Austin's Classification Proccess and Analysis

*Insert text here*

# Dannys's Classification Proccess and Analysis

*Insert text here*

# Ethans's Regression Proccess and Analysis

*Insert text here*







# Analysis Summary

*Insert text here*

# Potential Improvements

*Insert text here*

# Works Cited

- Breast Cancer Wisconsin (Diagnostic) Data Set:
    - https://www.kaggle.com/datasets/uciml/breast-cancer-wisconsin-data?datasetId=180&sortBy=voteCount
- Definition of Features (Variables):
    - https://www.causeweb.org/usproc/sites/default/files/usclap/2017-2/Evaluating_Benign_and_Malignant_Breast_Cancer_Cells_from_Fine-Needle_Aspirates.pdf