---
title: "Characterizing breast cancer cells"
author: Austin Lackey, Ethan Powers and Danny Laposata
date: Friday, November 9th, 2022
output: powerpoint_presentation
---

## The data

- We have a dataset of 569 breast cancer cells, some of which are cancerous and some of which are benign.
- We have 30 features for each cell, which are the measurements of the cell.
- We have a binary variable, `diagnosis`, which is `M` for malignant and `B` for benign.
- Add more stuff here...

## Sample Output
```{r, echo=FALSE, message=FALSE, warning=FALSE, results=FALSE}
library(tidyverse)
library(ggplot2)
library(dplyr)
library(caret)
set.seed(420)
data <- read.csv("breast_cancer_diagnostic_data.csv")
data <- subset(data, select = -c(X))
split <- sample(c(rep(0, 0.6 * nrow(data)), rep(1, 0.4 * nrow(data))))
train <- data[split == 0, ]
test <- data[split== 1, ]
#write.csv(train,"training.csv", row.names = FALSE)
#write.csv(test,"test.csv", row.names = FALSE)
```

```{r, echo=FALSE}
#histogram
print(ggplot(data, aes(x = diagnosis)) + geom_bar(aes(fill=diagnosis)) + labs(title = "Histogram of Diagnosis", x = "Diagnosis", y = "Count", fill="Diagnosis"))
```

## Plot
```{r, echo=FALSE}
#scatterplot
print(ggplot(data, aes(x = radius_mean, y = texture_mean, color = diagnosis)) + geom_point() + 
    labs(title = "Scatterplot of Radius Mean vs Texture Mean", x = "Radius Mean", y = "Texture Mean", color="Diagnosis"))
```

## Works Cited

- Insert link to kaggle dataset here